name: basic-build-and-ci
on:   [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: dependencies
        run: >
          sudo apt-get install --yes gcc
          make perl-base pkg-config
          libdevmapper-dev libreadline-dev libaio-dev libsystemd-dev
          libudev-dev libjson-c-dev liburcu-dev libcmocka-dev
      - name: build
        run: make -O -j$(grep -c ^processor /proc/cpuinfo)
      - name: test
        run: make -O -j$(grep -c ^processor /proc/cpuinfo) test
